** ComfyUI start up time: 2023-11-18 02:25:39.861489

Prestartup times for custom nodes:
   0.0 seconds: /src/ComfyUI/custom_nodes/ComfyUI-Manager

Total VRAM 24240 MB, total RAM 128650 MB
Set vram state to: NORMAL_VRAM
Device: cuda:0 NVIDIA RTX A5000 : cudaMallocAsync
VAE dtype: torch.bfloat16
Using pytorch cross attention
### Loading: ComfyUI-Manager (V1.0.1)
## ComfyUI-Manager: installing dependencies
 Collecting GitPython
   Downloading GitPython-3.1.40-py3-none-any.whl (190 kB)
      ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 190.6/190.6 kB 3.3 MB/s eta 0:00:00
 Collecting matrix-client==0.4.0
   Downloading matrix_client-0.4.0-py2.py3-none-any.whl (43 kB)
      ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 43.5/43.5 kB 3.4 MB/s eta 0:00:00
 Requirement already satisfied: requests~=2.22 in /root/.pyenv/versions/3.10.6/lib/python3.10/site-packages (from matrix-client==0.4.0->-r /src/ComfyUI/custom_nodes/ComfyUI-Manager/requirements.txt (line 2)) (2.31.0)
 Collecting urllib3~=1.21
   Downloading urllib3-1.26.18-py2.py3-none-any.whl (143 kB)
      ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 143.8/143.8 kB 5.5 MB/s eta 0:00:00
 Collecting gitdb<5,>=4.0.1
   Downloading gitdb-4.0.11-py3-none-any.whl (62 kB)
      ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 62.7/62.7 kB 3.9 MB/s eta 0:00:00
 Collecting smmap<6,>=3.0.1
   Downloading smmap-5.0.1-py3-none-any.whl (24 kB)
 Requirement already satisfied: certifi>=2017.4.17 in /root/.pyenv/versions/3.10.6/lib/python3.10/site-packages (from requests~=2.22->matrix-client==0.4.0->-r /src/ComfyUI/custom_nodes/ComfyUI-Manager/requirements.txt (line 2)) (2023.7.22)
 Requirement already satisfied: idna<4,>=2.5 in /root/.pyenv/versions/3.10.6/lib/python3.10/site-packages (from requests~=2.22->matrix-client==0.4.0->-r /src/ComfyUI/custom_nodes/ComfyUI-Manager/requirements.txt (line 2)) (3.4)
 Requirement already satisfied: charset-normalizer<4,>=2 in /root/.pyenv/versions/3.10.6/lib/python3.10/site-packages (from requests~=2.22->matrix-client==0.4.0->-r /src/ComfyUI/custom_nodes/ComfyUI-Manager/requirements.txt (line 2)) (3.3.2)
 Installing collected packages: urllib3, smmap, gitdb, matrix-client, GitPython
   Attempting uninstall: urllib3
     Found existing installation: urllib3 2.1.0
     Uninstalling urllib3-2.1.0:
       Successfully uninstalled urllib3-2.1.0
 Successfully installed GitPython-3.1.40 gitdb-4.0.11 matrix-client-0.4.0 smmap-5.0.1 urllib3-1.26.18
[!] WARNING: Running pip as the 'root' user can result in broken permissions and conflicting behaviour with the system package manager. It is recommended to use a virtual environment instead: https://pip.pypa.io/warnings/venv
[!] 
[!] [notice] A new release of pip available: 22.2.1 -> 23.3.1
[!] [notice] To update, run: pip install --upgrade pip
## ComfyUI-Manager: installing dependencies done.
### ComfyUI Revision: 1699 [0cf4e869] | Released on '2023-11-17'


Full error log from comfyui_controlnet_aux: 
Traceback (most recent call last):
  File "/src/ComfyUI/custom_nodes/comfyui_controlnet_aux/__init__.py", line 33, in load_nodes
    module = importlib.import_module(
  File "/root/.pyenv/versions/3.10.6/lib/python3.10/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1050, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1006, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 688, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/src/ComfyUI/custom_nodes/comfyui_controlnet_aux/node_wrappers/dwpose.py", line 5, in <module>
    from controlnet_aux.dwpose import DwposeDetector, AnimalposeDetector
  File "/src/ComfyUI/custom_nodes/comfyui_controlnet_aux/src/controlnet_aux/dwpose/__init__.py", line 16, in <module>
    from . import util
  File "/src/ComfyUI/custom_nodes/comfyui_controlnet_aux/src/controlnet_aux/dwpose/util.py", line 3, in <module>
    import matplotlib
ModuleNotFoundError: No module named 'matplotlib'



[36;20m[comfyui_controlnet_aux] | INFO -> Some nodes failed to load:
	Failed to import module dwpose because ModuleNotFoundError: No module named 'matplotlib'

Check that you properly installed the dependencies.
If you think this is a bug, please report it on the github page (https://github.com/Fannovel16/comfyui_controlnet_aux/issues)[0m
Adding /src/ComfyUI/custom_nodes to sys.path
Could not find efficiency nodes


Full error log from comfyui_controlnet_aux: 
Traceback (most recent call last):
  File "/src/ComfyUI/custom_nodes/comfyui_controlnet_aux/__init__.py", line 33, in load_nodes
    module = importlib.import_module(
  File "/root/.pyenv/versions/3.10.6/lib/python3.10/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1050, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1006, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 688, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/src/ComfyUI/custom_nodes/comfyui_controlnet_aux/node_wrappers/dwpose.py", line 5, in <module>
    from controlnet_aux.dwpose import DwposeDetector, AnimalposeDetector
  File "/src/ComfyUI/custom_nodes/comfyui_controlnet_aux/src/controlnet_aux/dwpose/__init__.py", line 16, in <module>
    from . import util
  File "/src/ComfyUI/custom_nodes/comfyui_controlnet_aux/src/controlnet_aux/dwpose/util.py", line 3, in <module>
    import matplotlib
ModuleNotFoundError: No module named 'matplotlib'



[36;20m[comfyui_controlnet_aux] | INFO -> Some nodes failed to load:
	Failed to import module dwpose because ModuleNotFoundError: No module named 'matplotlib'

Check that you properly installed the dependencies.
If you think this is a bug, please report it on the github page (https://github.com/Fannovel16/comfyui_controlnet_aux/issues)[0m
Loaded ControlNetPreprocessors nodes from /src/ComfyUI/custom_nodes/comfyui_controlnet_aux
Could not find AnimateDiff nodes
Loaded IPAdapter nodes from /src/ComfyUI/custom_nodes/ComfyUI_IPAdapter_plus
Traceback (most recent call last):
  File "/src/ComfyUI/nodes.py", line 1735, in load_custom_node
    module_spec.loader.exec_module(module)
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/src/ComfyUI/custom_nodes/comfyui-art-venture/__init__.py", line 10, in <module>
    from .modules.nodes import NODE_CLASS_MAPPINGS, NODE_DISPLAY_NAME_MAPPINGS
  File "/src/ComfyUI/custom_nodes/comfyui-art-venture/modules/nodes.py", line 55, in <module>
    from .inpaint import (
  File "/src/ComfyUI/custom_nodes/comfyui-art-venture/modules/inpaint/__init__.py", line 1, in <module>
    from .nodes import NODE_CLASS_MAPPINGS, NODE_DISPLAY_NAME_MAPPINGS
  File "/src/ComfyUI/custom_nodes/comfyui-art-venture/modules/inpaint/nodes.py", line 7, in <module>
    from .sam.nodes import SAMLoader, GetSAMEmbedding, SAMEmbeddingToImage
  File "/src/ComfyUI/custom_nodes/comfyui-art-venture/modules/inpaint/sam/nodes.py", line 4, in <module>
    from segment_anything import SamPredictor, sam_model_registry
ModuleNotFoundError: No module named 'segment_anything'

Cannot import /src/ComfyUI/custom_nodes/comfyui-art-venture module for custom nodes: No module named 'segment_anything'
WARNING: pip is being invoked by an old script wrapper. This will fail in a future version of pip.
Please see https://github.com/pypa/pip/issues/5599 for advice on fixing the underlying issue.
To avoid this problem you can invoke Python with '-m pip' instead of running pip directly.
Collecting matplotlib
  Downloading matplotlib-3.8.2-cp310-cp310-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (11.6 MB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 11.6/11.6 MB 10.3 MB/s eta 0:00:00
Collecting cycler>=0.10
  Downloading cycler-0.12.1-py3-none-any.whl (8.3 kB)
Collecting fonttools>=4.22.0
  Downloading fonttools-4.44.3-cp310-cp310-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (4.5 MB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 4.5/4.5 MB 7.6 MB/s eta 0:00:00
Collecting kiwisolver>=1.3.1
  Downloading kiwisolver-1.4.5-cp310-cp310-manylinux_2_12_x86_64.manylinux2010_x86_64.whl (1.6 MB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 1.6/1.6 MB 10.1 MB/s eta 0:00:00
Requirement already satisfied: numpy<2,>=1.21 in /root/.pyenv/versions/3.10.6/lib/python3.10/site-packages (from matplotlib) (1.26.2)
Collecting contourpy>=1.0.1
  Downloading contourpy-1.2.0-cp310-cp310-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (310 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 310.7/310.7 kB 9.6 MB/s eta 0:00:00
Requirement already satisfied: pillow>=8 in /root/.pyenv/versions/3.10.6/lib/python3.10/site-packages (from matplotlib) (10.1.0)
Collecting pyparsing>=2.3.1
  Downloading pyparsing-3.1.1-py3-none-any.whl (103 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 103.1/103.1 kB 10.6 MB/s eta 0:00:00
Requirement already satisfied: packaging>=20.0 in /root/.pyenv/versions/3.10.6/lib/python3.10/site-packages (from matplotlib) (23.2)
Collecting python-dateutil>=2.7
  Downloading python_dateutil-2.8.2-py2.py3-none-any.whl (247 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 247.7/247.7 kB 11.0 MB/s eta 0:00:00
Collecting six>=1.5
  Downloading six-1.16.0-py2.py3-none-any.whl (11 kB)
Installing collected packages: six, pyparsing, kiwisolver, fonttools, cycler, contourpy, python-dateutil, matplotlib
Successfully installed contourpy-1.2.0 cycler-0.12.1 fonttools-4.44.3 kiwisolver-1.4.5 matplotlib-3.8.2 pyparsing-3.1.1 python-dateutil-2.8.2 six-1.16.0
WARNING: Running pip as the 'root' user can result in broken permissions and conflicting behaviour with the system package manager. It is recommended to use a virtual environment instead: https://pip.pypa.io/warnings/venv

[notice] A new release of pip available: 22.2.1 -> 23.3.1
[notice] To update, run: pip install --upgrade pip
generated new fontManager
[34mComfyroll Custom Nodes: [92mLoaded[0m
Note: NumExpr detected 48 cores but "NUMEXPR_MAX_THREADS" not set, so enforcing safe limit of 8.
NumExpr defaulting to 8 threads.
Traceback (most recent call last):
  File "/src/ComfyUI/nodes.py", line 1735, in load_custom_node
    module_spec.loader.exec_module(module)
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/src/ComfyUI/custom_nodes/ComfyUI_FizzNodes/__init__.py", line 57, in <module>
    from .ScheduledNodes import (
  File "/src/ComfyUI/custom_nodes/ComfyUI_FizzNodes/ScheduledNodes.py", line 7, in <module>
    import pandas as pd
ModuleNotFoundError: No module named 'pandas'

Cannot import /src/ComfyUI/custom_nodes/ComfyUI_FizzNodes module for custom nodes: No module named 'pandas'
[92m[tinyterraNodes] [32mLoaded[0m

Import times for custom nodes:
   0.0 seconds: /src/ComfyUI/custom_nodes/ComfyUI_IPAdapter_plus
   0.0 seconds: /src/ComfyUI/custom_nodes/ComfyUi_NNLatentUpscale
   0.0 seconds: /src/ComfyUI/custom_nodes/ComfyUI-Advanced-ControlNet
   0.0 seconds: /src/ComfyUI/custom_nodes/ComfyUI-AnimateDiff-Evolved
   0.0 seconds (IMPORT FAILED): /src/ComfyUI/custom_nodes/ComfyUI_FizzNodes
   0.0 seconds (IMPORT FAILED): /src/ComfyUI/custom_nodes/comfyui-art-venture
   0.0 seconds: /src/ComfyUI/custom_nodes/comfyui_controlnet_aux
   0.0 seconds: /src/ComfyUI/custom_nodes/ComfyUI_tinyterraNodes
   0.1 seconds: /src/ComfyUI/custom_nodes/ComfyUI-VideoHelperSuite
   2.6 seconds: /src/ComfyUI/custom_nodes/ComfyUI-Manager
  10.7 seconds: /src/ComfyUI/custom_nodes/ComfyUI_Comfyroll_CustomNodes

Starting server

To see the GUI go to: http://127.0.0.1:8188
got prompt
model_type EPS
adm 0
Using pytorch attention in VAE
Working with z of shape (1, 4, 32, 32) = 4096 dimensions.
Using pytorch attention in VAE
missing {'cond_stage_model.clip_l.text_projection', 'cond_stage_model.clip_l.logit_scale'}
left over keys: dict_keys(['cond_stage_model.clip_l.transformer.text_model.embeddings.position_ids'])
[AnimateDiffEvo] - [0;32mINFO[0m - Loading motion module temporaldiff-v1-animatediff.safetensors
[AnimateDiffEvo] - [0;32mINFO[0m - Using fp16, converting motion module to fp16
Requested to load SD1ClipModel
Loading 1 new model
[AnimateDiffEvo] - [0;32mINFO[0m - Regular AnimateDiff activated - latents passed in (16) less or equal to context_length 16.
[AnimateDiffEvo] - [0;32mINFO[0m - Injecting motion module temporaldiff-v1-animatediff.safetensors version v1.
Requested to load BaseModel
Loading 1 new model
100%|██████████| 20/20 [00:17<00:00,  1.17it/s]100%|██████████| 20/20 [00:17<00:00,  1.17it/s]
[AnimateDiffEvo] - [0;32mINFO[0m - Ejecting motion module temporaldiff-v1-animatediff.safetensors version v1.
[AnimateDiffEvo] - [0;32mINFO[0m - Cleaning motion module from unet.
[AnimateDiffEvo] - [0;32mINFO[0m - Removing motion module temporaldiff-v1-animatediff.safetensors from cache
Global Step: 840001
Using pytorch attention in VAE
Working with z of shape (1, 4, 32, 32) = 4096 dimensions.
Using pytorch attention in VAE
Leftover VAE keys ['model_ema.decay', 'model_ema.num_updates']
Prompt executed in 20.90 seconds
